service: vehicle-counter-service
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1 # Replace with your desired AWS region
  timeout: 30
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource: arn:aws:s3:::cam-capture-bucket/*

functions:
  vehicleCounter:
    handler: handler.lambda_handler # Path to your Lambda handler function
    environment:
      BUCKET_NAME: cam-capture-bucket
    events:
      - s3:
          bucket: cam-capture-bucket
          event: s3:ObjectCreated:*
