service: lambda-mongodb
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1  # Change this to your desired AWS region
  stage: dev
  memorySize: 256
  timeout: 10

functions:
  saveLocation:
    handler: handler.handler
    environment:
      MONGODB_URI: 'mongodb+srv://krishnsundaram:zZdqmFc1hh9SJ8PG@cluster0.wyvjx1u.mongodb.net/'  # Replace with your MongoDB connection details
      COLLECTION_NAME: 'location'
    events:
      - http:
          path: save-location
          method: post

plugins:
  - serverless-offline

# You may need to add other IAM permissions or VPC configurations if required.
