service: lambda-mongodb
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1 # Replace with your desired AWS region

functions:
  saveLocation:
    handler: handler.handler
    events:
      - http:
          path: save-location
          method: post
    environment:
      DYNAMODB_TABLE: LocationData # Replace with your DynamoDB table name

plugins:
  - serverless-offline

resources:
  Resources:
    LocationDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: LocationId
            AttributeType: S
        KeySchema:
          - AttributeName: LocationId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

custom:
  serverless-offline:
    httpPort: 3000
